name: BruhCMD
version: 1.8.1
author: Icynnac
main: me.icynnac.bruhcmd.Main
api-version: 1.13
description: a dumb little plugin to do dumb things
commands:
  bruh:
    description: The command I thought of on that November 15th, 2020.
  bruh reload:
    description: Reloads the config.yml
    permission: bruhcmd.reload
  sus:
    description: AMOGUS??? OMG SO SUSSY!!!!
    permission: bruhcmd.sus
  cutg:
    description: someone likes ya cut g
    permission: bruhcmd.cutg
  yeet:
    description: yeet yourself into the stratosphere.
    permission: bruhcmd.yeet
  pop:
    description: pop c at
  bruhcmd:
    description: a ui for basic stuff in bruhcmd
    permission: bruhcmd.about
  joe:
    description: joe mama joke xd lol
    permission: bruhcmd.joe
  cyberpunk:
    description: wake the heck up samurai, we have a city to bruh
    permission: bruhcmd.cyberpunk
  bomb:
    description: boom.
    permission: bruhcmd.bomb
  creeper:
    description: awww man
    permission: bruhcmd.creeper
  dragon:
    description: DEEZ NU-
    permission: bruhcmd.deez
  bruhconfig:
    description: Edit config from game
    permission: bruhcmd.config
  syeet:
    description: SUPER YEEEEEET
    permission: bruhcmd.superyeet
  ratio:
    description: ratio + L + yb better
    permission: bruhcmd.ratio